<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatchRequestsSeeder extends Seeder
{
    public function run()
    {
        DB::table('match_requests')->insert([
            [
                'match_request_byClubID'       => '10',
                'match_request_againstClubID'  => '11',
                'matchRequestByTeamID'         => '1',
                'matchRequestAgainstTeamID'    => '2',
                'match_request_category'       => 'T',
                'match_request_overs'          => 'T20',
                'match_request_title'          => 'Karachi vs Lahore T20',
                'match_request_description'    => 'Friendly T20 clash between Karachi Strikers and Lahore Lions.',
                'match_request_dayDate'        => '2024-03-15',
                'match_request_dayTime'        => '14:00',
                'match_request_groundID'       => 1,
                'match_request_status'         => 'A',
                'match_request_winningTeam'    => '1',
                'match_request_winByRuns'      => '25',
                'match_request_winByWickets'   => null,
                'created_at'                   => now(),
                'updated_at'                   => now(),
            ],
            [
                'match_request_byClubID'       => '12',
                'match_request_againstClubID'  => '13',
                'matchRequestByTeamID'         => '3',
                'matchRequestAgainstTeamID'    => '4',
                'match_request_category'       => 'T',
                'match_request_overs'          => '1D',
                'match_request_title'          => 'Islamabad vs Rawalpindi One Day',
                'match_request_description'    => 'One-day inter-city rivalry match at Diamond Ground.',
                'match_request_dayDate'        => '2024-03-22',
                'match_request_dayTime'        => '09:00',
                'match_request_groundID'       => 3,
                'match_request_status'         => 'A',
                'match_request_winningTeam'    => '4',
                'match_request_winByRuns'      => null,
                'match_request_winByWickets'   => '3',
                'created_at'                   => now(),
                'updated_at'                   => now(),
            ],
            [
                'match_request_byClubID'       => '14',
                'match_request_againstClubID'  => '10',
                'matchRequestByTeamID'         => '5',
                'matchRequestAgainstTeamID'    => '1',
                'match_request_category'       => 'H',
                'match_request_overs'          => 'T20',
                'match_request_title'          => 'Peshawar vs Karachi Home T20',
                'match_request_description'    => 'Home fixture at Arbab Niaz Stadium.',
                'match_request_dayDate'        => '2024-04-05',
                'match_request_dayTime'        => '15:00',
                'match_request_groundID'       => 5,
                'match_request_status'         => 'P',
                'match_request_winningTeam'    => null,
                'match_request_winByRuns'      => null,
                'match_request_winByWickets'   => null,
                'created_at'                   => now(),
                'updated_at'                   => now(),
            ],
            [
                'match_request_byClubID'       => '11',
                'match_request_againstClubID'  => '14',
                'matchRequestByTeamID'         => '2',
                'matchRequestAgainstTeamID'    => '5',
                'match_request_category'       => 'T',
                'match_request_overs'          => 'SS',
                'match_request_title'          => 'Lahore vs Peshawar Super Six',
                'match_request_description'    => 'Super-six format fast game at Gaddafi Stadium.',
                'match_request_dayDate'        => '2024-04-12',
                'match_request_dayTime'        => '18:00',
                'match_request_groundID'       => 2,
                'match_request_status'         => 'A',
                'match_request_winningTeam'    => '2',
                'match_request_winByRuns'      => '10',
                'match_request_winByWickets'   => null,
                'created_at'                   => now(),
                'updated_at'                   => now(),
            ],
            [
                'match_request_byClubID'       => '13',
                'match_request_againstClubID'  => '12',
                'matchRequestByTeamID'         => '4',
                'matchRequestAgainstTeamID'    => '3',
                'match_request_category'       => 'H',
                'match_request_overs'          => 'T',
                'match_request_title'          => 'Rawalpindi vs Islamabad Test',
                'match_request_description'    => 'Two-day club-level test match at Pindi Cricket Stadium.',
                'match_request_dayDate'        => '2024-04-20',
                'match_request_dayTime'        => '10:00',
                'match_request_groundID'       => 4,
                'match_request_status'         => 'R',
                'match_request_winningTeam'    => null,
                'match_request_winByRuns'      => null,
                'match_request_winByWickets'   => null,
                'created_at'                   => now(),
                'updated_at'                   => now(),
            ],
        ]);
    }
}
